### ISSUE TITLE
Library pubsubclient

### ISSUE THREAD

**Issue by dylom** [DuchkPy/MQTT2Ravelli#1]
Hi, which version of library did you used in your project?

**Comment by DuchkPy** [comment]
Hello @dylom 

I'm using the version 2.8.0 
![image](https://user-images.githubusercontent.com/36851093/208391736-7645b1f1-47df-4145-9193-7429ec6be3a9.png)

Also, I just publish an update of the code that was outdated on this project compare to my local file (sorry for that).

Please give me a feedback here if it helps improving potential problem you were facing.
