### ISSUE TITLE
Ravelli RC70

### ISSUE THREAD

**Issue by esavalle** [DuchkPy/MQTT2Ravelli#10]
Hi there,

I would like to integrate your code into my Ravelli RC70 stove. On this one, the TOUCH remote control doesn't exist, but I have a 4-pin "Serial" port behind the stove's main screen. 
On the multimeter, I measure a GND pin, a 3.3V pin and a 12V pin. I have no information on the fourth pin.
Do you have any idea what I can test to see if the stove can be controlled by your work?

Cheers,

**Comment by DuchkPy** [comment]
Hello @esavalle,

The `serial` port is to connect another interface than the one on this project.
I know that the WiFi remote connection sold by Ravelli can be plugged-in there.

The project here needs to be plugged on the `remote` port.

**Comment by esavalle** [comment]
Thank you for your answer. Although I will not be able to use your project, I found this : https://esphome.io/components/micronova.html which should be what I need !
